name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Check for lookaside URLs
        run: |
          python scripts/check_for_lookaside_urls.py

      - name: Security scan summary
        if: failure()
        run: |
          echo "🔒 Security check failed!"
          echo "📋 Please review the lookaside URL violations above and fix them using get_media_download_url_from_id() instead."
          echo "🔗 See WhatsApp Business API documentation for secure media URL handling."
